# Generated by Django 2.0.4 on 2018-09-14 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Is the user allowed to have access to the admin', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Is the user account currently active', verbose_name='active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('binance_api_key', models.CharField(blank=True, default='', max_length=300)),
                ('binance_secret_key', models.CharField(blank=True, default='', max_length=300)),
                ('hitbtc_api_key', models.CharField(blank=True, default='', max_length=300)),
                ('hitbtc_secret_key', models.CharField(blank=True, default='', max_length=300)),
                ('poloniex_api_key', models.CharField(blank=True, default='', max_length=300)),
                ('poloniex_secret_key', models.CharField(blank=True, default='', max_length=300)),
                ('coinbase_api_key', models.CharField(blank=True, default='', max_length=300)),
                ('coinbase_secret_key', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
