# Generated by Django 2.0.4 on 2018-11-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
