# Generated by Django 2.0.4 on 2018-11-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='value',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='balance',
            name='usd_value',
            field=models.FloatField(default=0),
        ),
    ]
