# Generated by Django 2.0.4 on 2018-11-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181126_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='usd_value',
            field=models.FloatField(default=0),
        ),
    ]
