# Generated by Django 2.0.4 on 2018-11-28 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_trade_usd_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.FloatField(default=0)),
                ('outcome', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
