# Generated by Django 2.0.4 on 2018-11-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='symbol',
            field=models.CharField(default='', max_length=30),
        ),
    ]
