# Generated by Django 2.0.4 on 2018-04-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='month_chart',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='week_chart',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='month_chart',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='week_chart',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='month_chart',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week_chart',
            field=models.TextField(default=None, null=True),
        ),
    ]
